//! build.rs - read migrations.toml, generate migration structs at compile time
//!
//! Output: $OUT_DIR/auto_migrations.rs
//! Included in lib.rs via include!

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=migrations.toml");

    let toml_str = fs::read_to_string("migrations.toml")
        .expect("Failed to read migrations.toml");

    let value: toml::Value = toml::from_str(&toml_str)
        .expect("Failed to parse migrations.toml");

    let migrations = value["migration"]
        .as_array()
        .expect("No [[migration]] array found in migrations.toml");

    let mut code = String::new();
    code.push_str("// ============================================================\n");
    code.push_str("//  Auto-generated - do not edit manually\n");
    code.push_str("//  Generated by build.rs from migrations.toml\n");
    code.push_str("// ============================================================\n\n");

    let mut reg_list = String::new();

    for mig in migrations {
        let name = mig["name"]
            .as_str()
            .expect("Each migration must have a 'name' field");
        let mig_type = mig["type"]
            .as_str()
            .expect("Each migration must have a 'type' field");
        let struct_name = format!("Mig_{}", name);

        match mig_type {
            "module" => {
                code.push_str(&format!(
                    "pub use crate::migrations::{}::Migration as {};\n\n",
                    name, struct_name
                ));
            }
            "sql_dir" => {
                let savepoint = mig["savepoint"]
                    .as_str()
                    .expect("sql_dir type requires a 'savepoint' field");
                let title = mig["title"]
                    .as_str()
                    .expect("sql_dir type requires a 'title' field");
                let down_sqls = mig["down"]
                    .as_array()
                    .expect("sql_dir type requires a 'down' array");

                code.push_str(&format!("pub struct {};\n\n", struct_name));
                code.push_str(&format!(
                    "impl MigrationName for {} {{\n    fn name(&self) -> &str {{ \"{}\" }}\n}}\n\n",
                    struct_name, name
                ));
                code.push_str(&format!(
                    "#[async_trait::async_trait]\nimpl MigrationTrait for {} {{\n",
                    struct_name
                ));
                code.push_str("    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {\n");
                code.push_str(&format!(
                    "        common::execute_sql_dir(manager, \"{}\", \"{}\", \"{}\").await\n",
                    name, savepoint, title
                ));
                code.push_str("    }\n\n");
                code.push_str("    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {\n");
                code.push_str("        common::execute_raw_sqls(manager, &[\n");
                for sql in down_sqls {
                    let sql_str = sql.as_str().expect("down array elements must be strings");
                    code.push_str(&format!("            \"{}\",\n", escape_rust_string(sql_str)));
                }
                code.push_str(&format!(
                    "        ], \"{}\", \"{} rollback\").await\n",
                    savepoint, title
                ));
                code.push_str("    }\n}\n\n");
            }
            "raw" => {
                let savepoint = mig["savepoint"]
                    .as_str()
                    .expect("raw type requires a 'savepoint' field");
                let title = mig["title"]
                    .as_str()
                    .expect("raw type requires a 'title' field");
                let up_sqls = mig["up"]
                    .as_array()
                    .expect("raw type requires an 'up' array");
                let down_sqls = mig["down"]
                    .as_array()
                    .expect("raw type requires a 'down' array");

                code.push_str(&format!("pub struct {};\n\n", struct_name));
                code.push_str(&format!(
                    "impl MigrationName for {} {{\n    fn name(&self) -> &str {{ \"{}\" }}\n}}\n\n",
                    struct_name, name
                ));
                code.push_str(&format!(
                    "#[async_trait::async_trait]\nimpl MigrationTrait for {} {{\n",
                    struct_name
                ));

                // up
                code.push_str("    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {\n");
                code.push_str("        common::execute_raw_sqls(manager, &[\n");
                for sql in up_sqls {
                    let sql_str = sql.as_str().expect("up array elements must be strings");
                    code.push_str(&format!("            \"{}\",\n", escape_rust_string(sql_str)));
                }
                code.push_str(&format!(
                    "        ], \"{}\", \"{}\").await\n",
                    savepoint, title
                ));
                code.push_str("    }\n\n");

                // down
                code.push_str("    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {\n");
                code.push_str("        common::execute_raw_sqls(manager, &[\n");
                for sql in down_sqls {
                    let sql_str = sql.as_str().expect("down array elements must be strings");
                    code.push_str(&format!("            \"{}\",\n", escape_rust_string(sql_str)));
                }
                code.push_str(&format!(
                    "        ], \"{}\", \"{} rollback\").await\n",
                    savepoint, title
                ));
                code.push_str("    }\n}\n\n");
            }
            other => panic!("Unknown migration type: {} (supported: sql_dir, raw, module)", other),
        }

        reg_list.push_str(&format!("        Box::new({}),\n", struct_name));
    }

    // Generate all_migrations() function
    code.push_str("pub fn all_migrations() -> Vec<Box<dyn MigrationTrait>> {\n    vec![\n");
    code.push_str(&reg_list);
    code.push_str("    ]\n}\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("auto_migrations.rs");
    fs::write(&dest_path, code).expect("Failed to write auto_migrations.rs");
}

/// Escape special characters in Rust string literals
fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\")
     .replace('"', "\\\"")
}
