[package]
name = "migration"
edition.workspace = true
publish.workspace = true
version.workspace = true

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
db = {path = "../db"}
anyhow = {workspace = true}
async-std = {workspace = true}
sea-orm = {workspace = true}
sea-orm-migration = {version = "1", features = ["sqlx-postgres","sqlx-sqlite","sqlx-mysql"]}

[build-dependencies]
toml = {workspace = true}
