[workspace]
members = [
  "bin",
  "api",
  "service",
  "middleware-fn",
  "utils",
  "configs",
  "db",
  "migration",
]
resolver = "2"


[workspace.package]
authors = ["lingdu <waong2005@126.com>"]
edition = "2021"
homepage = "https://314.iu1314.top"
license = "Apache-2.0"
publish = false
repository = ""
version = "0.1.0"

[workspace.dependencies]
# axum
axum = { version = "0", features = ["http2", "original-uri", "multipart"] }
axum-extra = { version = "0", features = ["typed-header"] }
axum-server = { version = "0", features = ["tls-rustls"] }
hyper = "1"
http-body-util = "0"
mime = "0"
rustls = { version = "0", features = ["aws-lc-rs"] }
tower = { version = "0", features = ["make"] }
tower-http = { version = "0", features = ["cors", "fs", "compression-gzip"] }
#
anyhow = "1"
futures = "0.3"

chrono = { version = "0", features = ["serde"] }
headers = "0"
jsonwebtoken = "9"
once_cell = "1"
scru128 = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "parking_lot",
  "signal",
] }
tokio-stream = '0'
toml = "0"
time = "0"
tracing = "0"
tracing-appender = "0"
tracing-subscriber = { version = "0", features = [
  "json",
  "env-filter",
  "local-time",
  "registry",
] }

delay_timer = "0"
reqwest = { version = "0", features = ["json", "rustls"] }
user-agent-parser = "0.3"

md5 = "0"
rand = "0"
sysinfo = "0"
captcha_rust = "0"

futures-util = "0"
sea-orm = { version = "1", features = [
  "macros",
  "runtime-tokio-rustls",
  "debug-print",
  "with-chrono",
] }
async-std = { version = "^1", features = ["attributes", "tokio1"] }


[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "z"   # Optimize for size.
panic = 'abort'
# strip = "symbols" # none(false) debuginfo symbols(true).
