//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub mod prelude;

pub mod seaql_migrations;
pub mod sys_dept;
pub mod sys_dict_data;
pub mod sys_dict_type;
pub mod sys_job;
pub mod sys_job_log;
pub mod sys_login_log;
pub mod sys_menu;
pub mod sys_oper_log;
pub mod sys_post;
pub mod sys_role;
pub mod sys_role_api;
pub mod sys_role_dept;
pub mod sys_user;
pub mod sys_user_online;
pub mod sys_user_post;
pub mod sys_user_role;
