//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::{
    sys_api_db::Entity as SysApiDb, sys_dept::Entity as SysDept, sys_dict_data::Entity as SysDictData, sys_dict_type::Entity as SysDictType, sys_job::Entity as SysJob,
    sys_job_log::Entity as SysJobLog, sys_login_log::Entity as SysLoginLog, sys_menu::Entity as SysMenu, sys_oper_log::Entity as SysOperLog, sys_post::Entity as SysPost,
    sys_role::Entity as SysRole, sys_role_api::Entity as SysRoleApi, sys_role_dept::Entity as SysRoleDept, sys_update_log::Entity as SysUpdateLog, sys_user::Entity as SysUser,
    sys_user_dept::Entity as SysUserDept, sys_user_online::Entity as SysUserOnline, sys_user_post::Entity as SysUserPost, sys_user_role::Entity as SysUserRole,
};
