/*
 * @Author: lingdu waong2005@126.com
 * @Date: 2022-07-16 21:50:11
 * @LastEditors: lingdu waong2005@126.com
 * @LastEditTime: 2022-10-22 11:17:25
 * @FilePath: \poem-admin\db\src\system\entities\prelude.rs
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub use super::sys_api_db::Entity as SysApiDb;
pub use super::sys_dept::Entity as SysDept;
pub use super::sys_dict_data::Entity as SysDictData;
pub use super::sys_dict_type::Entity as SysDictType;
pub use super::sys_job::Entity as SysJob;
pub use super::sys_job_log::Entity as SysJobLog;
pub use super::sys_login_log::Entity as SysLoginLog;
pub use super::sys_menu::Entity as SysMenu;
pub use super::sys_oper_log::Entity as SysOperLog;
pub use super::sys_post::Entity as SysPost;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_role_api::Entity as SysRoleApi;
pub use super::sys_role_dept::Entity as SysRoleDept;
pub use super::sys_update_log::Entity as SysUpdateLog;
pub use super::sys_user::Entity as SysUser;
pub use super::sys_user_dept::Entity as SysUserDept;
pub use super::sys_user_online::Entity as SysUserOnline;
pub use super::sys_user_post::Entity as SysUserPost;
pub use super::sys_user_role::Entity as SysUserRole;
