//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub use super::sys_api_db::Entity as SysApiDb;
pub use super::sys_dept::Entity as SysDept;
pub use super::sys_dict_data::Entity as SysDictData;
pub use super::sys_dict_type::Entity as SysDictType;
pub use super::sys_job::Entity as SysJob;
pub use super::sys_job_log::Entity as SysJobLog;
pub use super::sys_login_log::Entity as SysLoginLog;
pub use super::sys_menu::Entity as SysMenu;
pub use super::sys_oper_log::Entity as SysOperLog;
pub use super::sys_post::Entity as SysPost;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_role_api::Entity as SysRoleApi;
pub use super::sys_role_dept::Entity as SysRoleDept;
pub use super::sys_update_log::Entity as SysUpdateLog;
pub use super::sys_user::Entity as SysUser;
pub use super::sys_user_dept::Entity as SysUserDept;
pub use super::sys_user_online::Entity as SysUserOnline;
pub use super::sys_user_post::Entity as SysUserPost;
pub use super::sys_user_role::Entity as SysUserRole;
