[package]
name = "app-service"
edition.workspace = true
publish.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#
configs = {path = "../configs"}
db = {path = "../db"}
utils = {path = "../utils"}
#  axum
axum = {workspace = true}
axum-extra = {workspace = true, features = ["typed-header"]}
#
anyhow = {workspace = true}
# 
chrono = {workspace = true, features = ["serde"]}
headers = {workspace = true}
jsonwebtoken = {workspace = true}
once_cell = {workspace = true}
# 
scru128 = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
tokio = {workspace = true}
#
tracing = {workspace = true}


# 计划任务
delay_timer = {workspace = true}
reqwest = {workspace = true, features = ["json"]}
user-agent-parser = {workspace = true}

#  随机数

# 系统信息
sysinfo = {workspace = true}
# 验证码
captcha_rust = {workspace = true}


# sea-orm
sea-orm = {workspace = true, features = ["macros", "runtime-tokio-native-tls", "debug-print"]}

[features]
default = ["postgres", "mysql", "sqlite"]
mysql = ["sea-orm/sqlx-mysql"]
postgres = ["sea-orm/sqlx-postgres"]
sqlite = ["sea-orm/sqlx-sqlite"]
