//! SeaORM Entity. Generated by sea-orm-codegen 0.4.0

pub mod prelude;

pub mod sys_auth_rule;
pub mod sys_config;
pub mod sys_dept;
pub mod sys_dict_data;
pub mod sys_dict_type;
pub mod sys_job;
pub mod sys_login_log;
pub mod sys_model_info;
pub mod sys_oper_log;
pub mod sys_post;
pub mod sys_role;
pub mod sys_role_dept;
pub mod sys_update_info;
pub mod sys_user;
pub mod sys_user_online;
pub mod sys_user_post;
pub mod sys_web_set;
