//! SeaORM Entity. Generated by sea-orm-codegen 0.3.2

pub use super::casbin_rule::Entity as CasbinRule;
pub use super::sys_auth_rule::Entity as SysAuthRule;
pub use super::sys_config::Entity as SysConfig;
pub use super::sys_dept::Entity as SysDept;
pub use super::sys_dict_data::Entity as SysDictData;
pub use super::sys_dict_type::Entity as SysDictType;
pub use super::sys_job::Entity as SysJob;
pub use super::sys_login_log::Entity as SysLoginLog;
pub use super::sys_model_info::Entity as SysModelInfo;
pub use super::sys_oper_log::Entity as SysOperLog;
pub use super::sys_post::Entity as SysPost;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_role_dept::Entity as SysRoleDept;
pub use super::sys_update_info::Entity as SysUpdateInfo;
pub use super::sys_user::Entity as SysUser;
pub use super::sys_user_online::Entity as SysUserOnline;
pub use super::sys_user_post::Entity as SysUserPost;
pub use super::sys_web_set::Entity as SysWebSet;
