//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

pub use super::{
    casbin_rule::Entity as CasbinRule, sys_config::Entity as SysConfig,
    sys_db_version::Entity as SysDbVersion, sys_dept::Entity as SysDept,
    sys_dict_data::Entity as SysDictData, sys_dict_type::Entity as SysDictType,
    sys_job::Entity as SysJob, sys_job_log::Entity as SysJobLog,
    sys_login_log::Entity as SysLoginLog, sys_menu::Entity as SysMenu,
    sys_model_info::Entity as SysModelInfo, sys_oper_log::Entity as SysOperLog,
    sys_post::Entity as SysPost, sys_role::Entity as SysRole, sys_role_dept::Entity as SysRoleDept,
    sys_update_info::Entity as SysUpdateInfo, sys_user::Entity as SysUser,
    sys_user_online::Entity as SysUserOnline, sys_user_post::Entity as SysUserPost,
    sys_web_set::Entity as SysWebSet,
};
