//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_menu")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub pid: String,
    #[sea_orm(unique)]
    pub name: String,
    pub title: String,
    pub icon: String,
    pub menu_type: i8,
    pub order_sort: i32,
    pub status: i8,
    pub path: String,
    pub jump_path: String,
    pub component: String,
    pub hidden: i8,
    pub keep_alive: i8,
    pub allow_data_scope: i8,
    pub is_data_scope: i8,
    pub is_frame: i8,
    pub module_type: String,
    pub model_id: i32,
    pub remark: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
