//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "sys_login_log"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub info_id: String,
    pub login_name: Option<String>,
    pub ipaddr: Option<String>,
    pub login_location: Option<String>,
    pub browser: Option<String>,
    pub os: Option<String>,
    pub status: Option<i8>,
    pub msg: Option<String>,
    pub login_time: Option<DateTime>,
    pub module: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    InfoId,
    LoginName,
    Ipaddr,
    LoginLocation,
    Browser,
    Os,
    Status,
    Msg,
    LoginTime,
    Module,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    InfoId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::InfoId => ColumnType::String(Some(32u32)).def(),
            Self::LoginName => ColumnType::String(Some(50u32)).def().null(),
            Self::Ipaddr => ColumnType::String(Some(50u32)).def().null(),
            Self::LoginLocation => ColumnType::String(Some(255u32)).def().null(),
            Self::Browser => ColumnType::String(Some(50u32)).def().null(),
            Self::Os => ColumnType::String(Some(50u32)).def().null(),
            Self::Status => ColumnType::TinyInteger.def().null(),
            Self::Msg => ColumnType::String(Some(255u32)).def().null(),
            Self::LoginTime => ColumnType::DateTime.def().null(),
            Self::Module => ColumnType::String(Some(30u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
