//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub user_name: String,
    #[sea_orm(unique)]
    pub mobile: String,
    pub user_nickname: String,
    pub birthday: i32,
    pub user_password: String,
    pub user_salt: String,
    pub user_status: i8,
    pub user_email: String,
    pub sex: i8,
    pub avatar: String,
    pub dept_id: String,
    pub remark: String,
    pub is_admin: i8,
    pub address: String,
    pub describe: String,
    pub phone_num: String,
    pub last_login_ip: String,
    pub last_login_time: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
